In [4]:
# imports
import requests
import pandas as pd
import os

# Foursquare

Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [28]:
df = pd.read_excel('dataframe.xlsx')

city = "bicincitta-assemini"
radius = 1000
api_key_fsq = os.environ["FOURSQUARE_API_KEY"]
latitude = df["Latitude"][0]
longitude = df["Longitude"][0]
url = "https://api.foursquare.com/v3/places/search?ll=" + str(latitude) + "%2C" + str(longitude) + "&radius=1000"

headers = {
    "accept": "application/json",
    "Authorization": api_key_fsq
}

response = requests.get(url, headers=headers)

data_fsq = response.json()
df

        City  Free Bikes   Latitude  Longitude
0   Assemini           4  39.296021   9.001761
1   Assemini           5  39.258480   9.153467
2   Assemini           0  39.287325   9.004893
3   Assemini           0  39.259166   9.137640
4   Assemini           0  39.254139   9.132729
5   Assemini           3  39.270203   9.049064
6   Assemini           0  39.287786   8.997803
7   Assemini           1  39.289455   9.006498
8   Assemini           4  39.294014   8.990276
9   Assemini           6  39.254040   9.165151
10  Assemini           4  39.264897   9.045739

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [56]:
location_data = []
for poi in data_fsq["results"]:
    location_info = {
        "name": poi["name"],
        "address":poi["location"]["address"],
        "latitude": poi["geocodes"]["main"]["latitude"],
        "longitude": poi["geocodes"]["main"]["longitude"]
    } 
    location_data.append(location_info)
location_data

[{'name': 'Shardana Beer Brothers',
  'address': 'Via Barbagia 38',
  'latitude': 39.294843,
  'longitude': 9.001885},
 {'name': 'Direzione Didattica Statale I Circolo',
  'address': 'Via di Vittorio',
  'latitude': 39.296126,
  'longitude': 9.000164},
 {'name': 'White Mage',
  'address': 'Via Baronia 8',
  'latitude': 39.295092,
  'longitude': 9.003318},
 {'name': 'Luxar Eat',
  'address': 'Via Sulcis 32',
  'latitude': 39.296916,
  'longitude': 9.003687},
 {'name': 'Casti Angela',
  'address': 'Via Barbagia 3',
  'latitude': 39.294007,
  'longitude': 9.002829},
 {'name': "C'Ã¨ Pizza Per Te",
  'address': 'Corso Africa 11',
  'latitude': 39.297121,
  'longitude': 8.999074},
 {'name': 'Antoniorossi.Info',
  'address': 'Via La Maddalena 2',
  'latitude': 39.298147,
  'longitude': 9.000169},
 {'name': 'Piscina Comunale Acquasport',
  'address': 'Via Riu Sa Murta 2',
  'latitude': 39.294891,
  'longitude': 9.004884},
 {'name': 'Su.Sa',
  'address': 'Viale Monastir',
  'latitude': 39.296066,
  'longitude': 8.998282},
 {'name': 'Dir. Did. I Circ',
  'address': 'Via di Vittorio 5',
  'latitude': 39.298349,
  'longitude': 8.999247}]

Put your parsed results into a DataFrame

In [34]:
df_four = pd.DataFrame(location_data)

# Display the DataFrame
df_four

,name,address,latitude,longitude
0,Shardana Beer Brothers,"Via Barbagia 38, 09032 Assemini Sardegna",39.294843,9.001885
1,Direzione Didattica Statale I Circolo,"Via di Vittorio, 09032 Assemini Sardegna",39.296126,9.000164
2,White Mage,"Via Baronia 8, 09032 Assemini Sardegna",39.295092,9.003318
3,Luxar Eat,"Via Sulcis 32, 09032 Assemini Sardegna",39.296916,9.003687
4,Casti Angela,"Via Barbagia 3, 09032 Assemini Sardegna",39.294007,9.002829
5,C'Ã¨ Pizza Per Te,"Corso Africa 11, 09032 Assemini Sardegna",39.297121,8.999074
6,Antoniorossi.Info,"Via La Maddalena 2, 09032 Assemini Sardegna",39.298147,9.000169
7,Piscina Comunale Acquasport,"Via Riu Sa Murta 2, 09032 Assemini Sardegna",39.294891,9.004884
8,Su.Sa,"Viale Monastir, 09028 Sestu Sardegna",39.296066,8.998282
9,Dir. Did. I Circ,"Via di Vittorio 5, 09032 Assemini Sardegna",39.298349,8.999247

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [78]:
url = "https://api.yelp.com/v3/businesses/search?latitude=" + str(latitude) + "&longitude=" + str(longitude) + "&radius=1000"
api_key_yelp = os.environ["YELP_API_KEY"]
headers = {
    "accept": "application/json",
    "Authorization": "Bearer " + api_key_yelp
}

response = requests.get(url, headers=headers)
data_yelp = response.json()

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [67]:
location_data_yelp = []
for poi in data_yelp["businesses"]:
    location_info_yelp = {
        "name": poi["name"],
        "rating": poi["rating"],
        "address":poi["location"]["address1"],
        "latitude": poi["coordinates"]["latitude"],
        "longitude": poi["coordinates"]["longitude"]
    } 
    location_data_yelp.append(location_info_yelp)
location_data_yelp

[{'name': 'Sardarivestimenti',
  'rating': 5.0,
  'address': 'Via Bologna 8',
  'latitude': 39.292,
  'longitude': 8.99371},
 {'name': 'Buzz',
  'rating': 4.5,
  'address': 'Via Sardegna 34',
  'latitude': 39.2876816,
  'longitude': 9.009778},
 {'name': 'Pizzeria La Brace di Dario Costantini',
  'rating': 5.0,
  'address': 'Via Dorgali, 1',
  'latitude': 39.2981,
  'longitude': 8.99593},
 {'name': 'Bed & breakfast',
  'rating': 3.0,
  'address': 'via cagliari 374',
  'latitude': 39.2929115,
  'longitude': 8.9937992}]

In [83]:
df_yelp = pd.DataFrame(location_data_yelp)
df_yelp

,name,rating,address,latitude,longitude
0,Sardarivestimenti,5.0,Via Bologna 8,39.292000,8.993710
1,Buzz,4.5,Via Sardegna 34,39.287682,9.009778
2,Pizzeria La Brace di Dario Costantini,5.0,"Via Dorgali, 1",39.298100,8.995930
3,Bed & breakfast,3.0,via cagliari 374,39.292912,8.993799

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

Yelp provided with more data(rating, phone number, opening hours) but less results than the foursquare API

Get the top 10 restaurants according to their rating

In [76]:
df_yelp.sort_values(by=['rating'], ascending=False)

,name,rating,address,latitude,longitude
0,Sardarivestimenti,5.0,Via Bologna 8,39.292000,8.993710
2,Pizzeria La Brace di Dario Costantini,5.0,"Via Dorgali, 1",39.298100,8.995930
1,Buzz,4.5,Via Sardegna 34,39.287682,9.009778
3,Bed & breakfast,3.0,via cagliari 374,39.292912,8.993799